apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: restarter-job
  namespace: default
spec:
  concurrencyPolicy: Forbid
  failedJobsHistoryLimit: 10
  jobTemplate:
    metadata:
      creationTimestamp: null
    spec:
      template:
        metadata:
          creationTimestamp: null
          labels:
            app: restarter-job
        spec:
          serviceAccountName: sa-service-restarter
          containers:
          - image: gcr.io/google.com/cloudsdktool/cloud-sdk:latest
            imagePullPolicy: IfNotPresent
            name: restarter-job
            resources:
              requests:
                memory: "64Mi"
                cpu: "250m"
              limits:
                memory: "128Mi"
                cpu: "500m"
            terminationMessagePath: /dev/termination-log
            terminationMessagePolicy: File
            command: 
              - "/bin/sh"
              - -c 
              - kubectl patch deployment $DEPLOYMENT_NAME -p '{"spec":{"template":{"metadata":{"labels":{"restarted-by":"'${POD_NAME}'"}}}}}'
            env:
            - name: DEPLOYMENT_NAME
              value: UPDATE_THIS
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
          dnsPolicy: ClusterFirst
          restartPolicy: OnFailure
          schedulerName: default-scheduler
          securityContext: {}
          terminationGracePeriodSeconds: 30
      backoffLimit: 4

  schedule: 0 */10 * * *
  successfulJobsHistoryLimit: 10
  suspend: false

