---
kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  namespace: default
  name: service-restarter
rules:
- apiGroups:
  - extensions
  - apps
  resources:
  - deployments
  - replicasets
  verbs:
  - 'patch'
  - 'get'
---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1beta1
metadata:
  name: service-restarter
  namespace: default
subjects:
- kind: ServiceAccount
  name: sa-service-restarter
  namespace: default
roleRef:
  kind: Role
  name: service-restarter
  apiGroup: ""
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: sa-service-restarter
  namespace: default

